### ISSUE TITLE
Cannot read parquet file using apache-parquet-java generated from nanoparquet

### ISSUE THREAD

**Issue by RealTYPICAL** [r-lib/nanoparquet#98]
When trying to use `MessageColumnIO` to get a record reader, the following error occurs:

```
Exception in thread "main" java.lang.UnsupportedOperationException
	at org.apache.parquet.column.values.ValuesReader.readInteger(ValuesReader.java:178)
	at org.apache.parquet.column.impl.ColumnReaderBase$ValuesReaderIntIterator.nextInt(ColumnReaderBase.java:830)
	at org.apache.parquet.column.impl.ColumnReaderBase.checkRead(ColumnReaderBase.java:663)
	at org.apache.parquet.column.impl.ColumnReaderBase.consume(ColumnReaderBase.java:801)
	at org.apache.parquet.column.impl.ColumnReaderImpl.consume(ColumnReaderImpl.java:30)
	at org.apache.parquet.column.impl.ColumnReaderImpl.<init>(ColumnReaderImpl.java:43)
	at org.apache.parquet.column.impl.ColumnReadStoreImpl.getColumnReader(ColumnReadStoreImpl.java:80)
	at org.apache.parquet.io.RecordReaderImplementation.<init>(RecordReaderImplementation.java:282)
	at org.apache.parquet.io.MessageColumnIO$1.visit(MessageColumnIO.java:141)
	at org.apache.parquet.io.MessageColumnIO$1.visit(MessageColumnIO.java:105)
	at org.apache.parquet.filter2.compat.FilterCompat$NoOpFilter.accept(FilterCompat.java:180)
	at org.apache.parquet.io.MessageColumnIO.getRecordReader(MessageColumnIO.java:105)
```

It seems like the rlEncoding and dlEncoding isn't specified properly when writing the parquet file in nanoparquet.

**Comment by gaborcsardi** [comment]
Can you please try to create reproducible example?

**Comment by gaborcsardi** [comment]
## Reprex

Install parquet-cli:
```
brew install parquet-cli
```

and then

```r
write_parquet(mtcars, "nano.parquet")
arrow::write_parquet(mtcars, "arrow.parquet")
```

```
❯ parquet  cat arrow.parquet                            
{"mpg": 21.0, "cyl": 6.0, "disp": 160.0, "hp": 110.0, "drat": 3.9, "wt": 2.62, "qsec": 16.46, "vs": 0.0, "am": 1.0, "gear": 4.0, "carb": 4.0}
{"mpg": 21.0, "cyl": 6.0, "disp": 160.0, "hp": 110.0, "drat": 3.9, "wt": 2.875, "qsec": 17.02, "vs": 0.0, "am": 1.0, "gear": 4.0, "carb": 4.0}
{"mpg": 22.8, "cyl": 4.0, "disp": 108.0, "hp": 93.0, "drat": 3.85, "wt": 2.32, "qsec": 18.61, "vs": 1.0, "am": 1.0, "gear": 4.0, "carb": 1.0}
{"mpg": 21.4, "cyl": 6.0, "disp": 258.0, "hp": 110.0, "drat": 3.08, "wt": 3.215, "qsec": 19.44, "vs": 1.0, "am": 0.0, "gear": 3.0, "carb": 1.0}
{"mpg": 18.7, "cyl": 8.0, "disp": 360.0, "hp": 175.0, "drat": 3.15, "wt": 3.44, "qsec": 17.02, "vs": 0.0, "am": 0.0, "gear": 3.0, "carb": 2.0}
{"mpg": 18.1, "cyl": 6.0, "disp": 225.0, "hp": 105.0, "drat": 2.76, "wt": 3.46, "qsec": 20.22, "vs": 1.0, "am": 0.0, "gear": 3.0, "carb": 1.0}
...
```

but 

```
❯ parquet  cat nano.parquet
Unknown error
java.lang.RuntimeException: Failed on record 0 in file nano.parquet
        at org.apache.parquet.cli.commands.CatCommand.runWithAvroSchema(CatCommand.java:101)
        at org.apache.parquet.cli.commands.CatCommand.run(CatCommand.java:67)
        at org.apache.parquet.cli.Main.run(Main.java:217)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
        at org.apache.parquet.cli.Main.main(Main.java:245)
Caused by: org.apache.parquet.io.ParquetDecodingException: Can not read value at 0 in block -1 in file file:/Users/gaborcsardi/works/nanoparquet/nano.parquet
        at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:280)
        at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:136)
        at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:140)
        at org.apache.parquet.cli.BaseCommand$2$1.advance(BaseCommand.java:505)
        at org.apache.parquet.cli.BaseCommand$2$1.<init>(BaseCommand.java:486)
        at org.apache.parquet.cli.BaseCommand$2.iterator(BaseCommand.java:484)
        at org.apache.parquet.cli.commands.CatCommand.runWithAvroSchema(CatCommand.java:88)
        ... 4 more
Caused by: java.lang.UnsupportedOperationException
        at org.apache.parquet.column.values.ValuesReader.readInteger(ValuesReader.java:178)
        at org.apache.parquet.column.impl.ColumnReaderBase$ValuesReaderIntIterator.nextInt(ColumnReaderBase.java:822)
        at org.apache.parquet.column.impl.ColumnReaderBase.checkRead(ColumnReaderBase.java:655)
        at org.apache.parquet.column.impl.ColumnReaderBase.consume(ColumnReaderBase.java:793)
        at org.apache.parquet.column.impl.ColumnReaderImpl.consume(ColumnReaderImpl.java:30)
        at org.apache.parquet.column.impl.ColumnReaderImpl.<init>(ColumnReaderImpl.java:43)
        at org.apache.parquet.column.impl.ColumnReadStoreImpl.getColumnReader(ColumnReadStoreImpl.java:80)
        at org.apache.parquet.io.RecordReaderImplementation.<init>(RecordReaderImplementation.java:282)
        at org.apache.parquet.io.MessageColumnIO$1.visit(MessageColumnIO.java:141)
        at org.apache.parquet.io.MessageColumnIO$1.visit(MessageColumnIO.java:105)
        at org.apache.parquet.filter2.compat.FilterCompat$NoOpFilter.accept(FilterCompat.java:186)
        at org.apache.parquet.io.MessageColumnIO.getRecordReader(MessageColumnIO.java:105)
        at org.apache.parquet.hadoop.InternalParquetRecordReader.checkRead(InternalParquetRecordReader.java:156)
        at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:245)
        ... 10 more
```
